title: "AstroLaureate"
global_title: "AstroLaureate"
baseurl: ""
url: "https://AstroLaureate.github.io"
content_path: "static/img/blog"
img_path: 'https://AstroLaureate.github.io/static/img/'
repository: AstroLaureate/AstroLaureate
github: [metadata]

# author
author:
  name: 'Samuel Hinton'
  first_name: 'Samuel'
  last_name: 'Hinton'
  email: 'samuelreay@gmail.com'

# sections
sections:
  - id: 'about-me'
    name: 'About'
    tpl: 'about.html'
    css: ''

  - id: 'home'
    name: 'Home'
    tpl: 'home.html'
    css: 'academia'



# google analytics
#ga:
#  id: UA-72691106-1

# Build settings
encoding: "utf-8"
exclude:
    - node_modules

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax

plugins:
  - jekyll-redirect-from